#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_PROJECT1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcategory_tb(category_tb instance);
    partial void Updatecategory_tb(category_tb instance);
    partial void Deletecategory_tb(category_tb instance);
    partial void Insertproduct_tb(product_tb instance);
    partial void Updateproduct_tb(product_tb instance);
    partial void Deleteproduct_tb(product_tb instance);
    partial void Inserttypes_tb(types_tb instance);
    partial void Updatetypes_tb(types_tb instance);
    partial void Deletetypes_tb(types_tb instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<category_tb> category_tbs
		{
			get
			{
				return this.GetTable<category_tb>();
			}
		}
		
		public System.Data.Linq.Table<product_tb> product_tbs
		{
			get
			{
				return this.GetTable<product_tb>();
			}
		}
		
		public System.Data.Linq.Table<types_tb> types_tbs
		{
			get
			{
				return this.GetTable<types_tb>();
			}
		}
		
		public System.Data.Linq.Table<users_tb> users_tbs
		{
			get
			{
				return this.GetTable<users_tb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category_tb")]
	public partial class category_tb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CATEGORY;
		
		private string _NAME_CATEGORY;
		
		private System.Nullable<System.DateTime> _PUBLISH_DATE;
		
		private EntitySet<types_tb> _types_tbs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CATEGORYChanging(int value);
    partial void OnID_CATEGORYChanged();
    partial void OnNAME_CATEGORYChanging(string value);
    partial void OnNAME_CATEGORYChanged();
    partial void OnPUBLISH_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPUBLISH_DATEChanged();
    #endregion
		
		public category_tb()
		{
			this._types_tbs = new EntitySet<types_tb>(new Action<types_tb>(this.attach_types_tbs), new Action<types_tb>(this.detach_types_tbs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORY", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_CATEGORY
		{
			get
			{
				return this._ID_CATEGORY;
			}
			set
			{
				if ((this._ID_CATEGORY != value))
				{
					this.OnID_CATEGORYChanging(value);
					this.SendPropertyChanging();
					this._ID_CATEGORY = value;
					this.SendPropertyChanged("ID_CATEGORY");
					this.OnID_CATEGORYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_CATEGORY", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_CATEGORY
		{
			get
			{
				return this._NAME_CATEGORY;
			}
			set
			{
				if ((this._NAME_CATEGORY != value))
				{
					this.OnNAME_CATEGORYChanging(value);
					this.SendPropertyChanging();
					this._NAME_CATEGORY = value;
					this.SendPropertyChanged("NAME_CATEGORY");
					this.OnNAME_CATEGORYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISH_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> PUBLISH_DATE
		{
			get
			{
				return this._PUBLISH_DATE;
			}
			set
			{
				if ((this._PUBLISH_DATE != value))
				{
					this.OnPUBLISH_DATEChanging(value);
					this.SendPropertyChanging();
					this._PUBLISH_DATE = value;
					this.SendPropertyChanged("PUBLISH_DATE");
					this.OnPUBLISH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_tb_types_tb", Storage="_types_tbs", ThisKey="ID_CATEGORY", OtherKey="ID_CATEGORE_TYPE")]
		public EntitySet<types_tb> types_tbs
		{
			get
			{
				return this._types_tbs;
			}
			set
			{
				this._types_tbs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_types_tbs(types_tb entity)
		{
			this.SendPropertyChanging();
			entity.category_tb = this;
		}
		
		private void detach_types_tbs(types_tb entity)
		{
			this.SendPropertyChanging();
			entity.category_tb = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_tb")]
	public partial class product_tb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PRODUCT;
		
		private string _NAME_PRODUCT;
		
		private System.Nullable<System.DateTime> _PUBLISH_DATE_P;
		
		private string _IS_VALIBLE;
		
		private EntitySet<types_tb> _types_tbs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PRODUCTChanging(int value);
    partial void OnID_PRODUCTChanged();
    partial void OnNAME_PRODUCTChanging(string value);
    partial void OnNAME_PRODUCTChanged();
    partial void OnPUBLISH_DATE_PChanging(System.Nullable<System.DateTime> value);
    partial void OnPUBLISH_DATE_PChanged();
    partial void OnIS_VALIBLEChanging(string value);
    partial void OnIS_VALIBLEChanged();
    #endregion
		
		public product_tb()
		{
			this._types_tbs = new EntitySet<types_tb>(new Action<types_tb>(this.attach_types_tbs), new Action<types_tb>(this.detach_types_tbs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_PRODUCT
		{
			get
			{
				return this._ID_PRODUCT;
			}
			set
			{
				if ((this._ID_PRODUCT != value))
				{
					this.OnID_PRODUCTChanging(value);
					this.SendPropertyChanging();
					this._ID_PRODUCT = value;
					this.SendPropertyChanged("ID_PRODUCT");
					this.OnID_PRODUCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_PRODUCT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_PRODUCT
		{
			get
			{
				return this._NAME_PRODUCT;
			}
			set
			{
				if ((this._NAME_PRODUCT != value))
				{
					this.OnNAME_PRODUCTChanging(value);
					this.SendPropertyChanging();
					this._NAME_PRODUCT = value;
					this.SendPropertyChanged("NAME_PRODUCT");
					this.OnNAME_PRODUCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISH_DATE_P", DbType="Date")]
		public System.Nullable<System.DateTime> PUBLISH_DATE_P
		{
			get
			{
				return this._PUBLISH_DATE_P;
			}
			set
			{
				if ((this._PUBLISH_DATE_P != value))
				{
					this.OnPUBLISH_DATE_PChanging(value);
					this.SendPropertyChanging();
					this._PUBLISH_DATE_P = value;
					this.SendPropertyChanged("PUBLISH_DATE_P");
					this.OnPUBLISH_DATE_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_VALIBLE", DbType="NChar(10)")]
		public string IS_VALIBLE
		{
			get
			{
				return this._IS_VALIBLE;
			}
			set
			{
				if ((this._IS_VALIBLE != value))
				{
					this.OnIS_VALIBLEChanging(value);
					this.SendPropertyChanging();
					this._IS_VALIBLE = value;
					this.SendPropertyChanged("IS_VALIBLE");
					this.OnIS_VALIBLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_tb_types_tb", Storage="_types_tbs", ThisKey="ID_PRODUCT", OtherKey="ID_PRODUCT_TYPE")]
		public EntitySet<types_tb> types_tbs
		{
			get
			{
				return this._types_tbs;
			}
			set
			{
				this._types_tbs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_types_tbs(types_tb entity)
		{
			this.SendPropertyChanging();
			entity.product_tb = this;
		}
		
		private void detach_types_tbs(types_tb entity)
		{
			this.SendPropertyChanging();
			entity.product_tb = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.types_tb")]
	public partial class types_tb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID_CATEGORE_TYPE;
		
		private System.Nullable<int> _ID_PRODUCT_TYPE;
		
		private string _TYPES_PRO;
		
		private int _ID_TYPE_CAT_PRO;
		
		private EntityRef<category_tb> _category_tb;
		
		private EntityRef<product_tb> _product_tb;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CATEGORE_TYPEChanging(System.Nullable<int> value);
    partial void OnID_CATEGORE_TYPEChanged();
    partial void OnID_PRODUCT_TYPEChanging(System.Nullable<int> value);
    partial void OnID_PRODUCT_TYPEChanged();
    partial void OnTYPES_PROChanging(string value);
    partial void OnTYPES_PROChanged();
    partial void OnID_TYPE_CAT_PROChanging(int value);
    partial void OnID_TYPE_CAT_PROChanged();
    #endregion
		
		public types_tb()
		{
			this._category_tb = default(EntityRef<category_tb>);
			this._product_tb = default(EntityRef<product_tb>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORE_TYPE", DbType="Int")]
		public System.Nullable<int> ID_CATEGORE_TYPE
		{
			get
			{
				return this._ID_CATEGORE_TYPE;
			}
			set
			{
				if ((this._ID_CATEGORE_TYPE != value))
				{
					if (this._category_tb.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CATEGORE_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ID_CATEGORE_TYPE = value;
					this.SendPropertyChanged("ID_CATEGORE_TYPE");
					this.OnID_CATEGORE_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCT_TYPE", DbType="Int")]
		public System.Nullable<int> ID_PRODUCT_TYPE
		{
			get
			{
				return this._ID_PRODUCT_TYPE;
			}
			set
			{
				if ((this._ID_PRODUCT_TYPE != value))
				{
					if (this._product_tb.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PRODUCT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ID_PRODUCT_TYPE = value;
					this.SendPropertyChanged("ID_PRODUCT_TYPE");
					this.OnID_PRODUCT_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPES_PRO", DbType="NChar(10)")]
		public string TYPES_PRO
		{
			get
			{
				return this._TYPES_PRO;
			}
			set
			{
				if ((this._TYPES_PRO != value))
				{
					this.OnTYPES_PROChanging(value);
					this.SendPropertyChanging();
					this._TYPES_PRO = value;
					this.SendPropertyChanged("TYPES_PRO");
					this.OnTYPES_PROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TYPE_CAT_PRO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_TYPE_CAT_PRO
		{
			get
			{
				return this._ID_TYPE_CAT_PRO;
			}
			set
			{
				if ((this._ID_TYPE_CAT_PRO != value))
				{
					this.OnID_TYPE_CAT_PROChanging(value);
					this.SendPropertyChanging();
					this._ID_TYPE_CAT_PRO = value;
					this.SendPropertyChanged("ID_TYPE_CAT_PRO");
					this.OnID_TYPE_CAT_PROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_tb_types_tb", Storage="_category_tb", ThisKey="ID_CATEGORE_TYPE", OtherKey="ID_CATEGORY", IsForeignKey=true)]
		public category_tb category_tb
		{
			get
			{
				return this._category_tb.Entity;
			}
			set
			{
				category_tb previousValue = this._category_tb.Entity;
				if (((previousValue != value) 
							|| (this._category_tb.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._category_tb.Entity = null;
						previousValue.types_tbs.Remove(this);
					}
					this._category_tb.Entity = value;
					if ((value != null))
					{
						value.types_tbs.Add(this);
						this._ID_CATEGORE_TYPE = value.ID_CATEGORY;
					}
					else
					{
						this._ID_CATEGORE_TYPE = default(Nullable<int>);
					}
					this.SendPropertyChanged("category_tb");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_tb_types_tb", Storage="_product_tb", ThisKey="ID_PRODUCT_TYPE", OtherKey="ID_PRODUCT", IsForeignKey=true)]
		public product_tb product_tb
		{
			get
			{
				return this._product_tb.Entity;
			}
			set
			{
				product_tb previousValue = this._product_tb.Entity;
				if (((previousValue != value) 
							|| (this._product_tb.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product_tb.Entity = null;
						previousValue.types_tbs.Remove(this);
					}
					this._product_tb.Entity = value;
					if ((value != null))
					{
						value.types_tbs.Add(this);
						this._ID_PRODUCT_TYPE = value.ID_PRODUCT;
					}
					else
					{
						this._ID_PRODUCT_TYPE = default(Nullable<int>);
					}
					this.SendPropertyChanged("product_tb");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users_tb")]
	public partial class users_tb
	{
		
		private string _FULL_NAME;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private string _AUTHORISE;
		
		public users_tb()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULL_NAME", DbType="NVarChar(50)")]
		public string FULL_NAME
		{
			get
			{
				return this._FULL_NAME;
			}
			set
			{
				if ((this._FULL_NAME != value))
				{
					this._FULL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHORISE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AUTHORISE
		{
			get
			{
				return this._AUTHORISE;
			}
			set
			{
				if ((this._AUTHORISE != value))
				{
					this._AUTHORISE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
